import{withScopeId as e,pushScopeId as t,popScopeId as n,openBlock as s,createBlock as a,defineComponent as o,ref as c,computed as r,createVNode as i,createApp as d}from"/web_modules/vue/vue.esm-browser.prod.js";
import{createRouter,createWebHistory}from"/web_modules/vue/vue-router.esm.js";

var l={};const p=e("data-v-51e68c33");t("data-v-51e68c33");const h={class:"hidden"};n();const u=p((function(t,e){return s(),a("div",h," home ")}));l.render=u,l.__scopeId="data-v-51e68c33";var m=o(l),v={};const w=e("data-v-f6d46782");t("data-v-f6d46782");const f={class:"hidden"};n();const g=w((function(t,e){return s(),a("div",f," contact.vue ")}));v.render=g,v.__scopeId="data-v-f6d46782";var b=o(v);const _=createWebHistory("/");let C=createRouter({history:_,routes:[{path:"/",component:m},{path:"/who",component:b},{path:"/what",component:b},{path:"/where",component:b},{path:"/when",component:b},{path:"/why",component:b}]});
var k={setup(){const t=c("start"),e=r(()=>"flex-auto text-center name title-transform--"+t.value);return{transformId:t,transformClass:e,trigger:function(r,e){t.value=r,C.push(e)}}}};
const y=e("data-v-e8ba3f3c");t("data-v-e8ba3f3c");const x={class:"flex mx-auto mt-5 mb-5 logo"},I=i("span",{class:"_w"},"w",-1),F=i("span",{class:"_e"},"e",-1),R=i("span",{class:"_b"},"b",-1);n();
const j=y((function(n,e){return s(),a("section",x,[i("h1",{class:n.transformClass},[i("span",{class:"s",onClick:e[1]||(e[1]=s=>n.trigger("s","who"))},"s"),i("span",{class:"e1",onClick:e[2]||(e[2]=s=>n.trigger("e1","what"))},"e"),i("span",{class:"n",onClick:e[3]||(e[3]=s=>n.trigger("n","where"))},"n"),i("span",{class:"e2",onClick:e[4]||(e[4]=s=>n.trigger("e2","when"))},"e"),i("span",{class:"i",onClick:e[5]||(e[5]=s=>n.trigger("i","why"))},"i"),i("small",{onClick:e[6]||(e[6]=s=>n.trigger("web","/"))},[I,F,R])],2)])}));
(k.render = j), (k.__scopeId = "data-v-e8ba3f3c");
const H = d(o(k));
H.use(C),H.mount("#senei"),window.senei=H,window.senei_router=C,new FontFaceObserver("StencilRough").load().then((function(){document.body.classList.add("has-stencil")}));